Feature Booking, SookingType, SubscriptionType entities
web-development-course-way/fms pull request #4
Opened 2024-03-19 20:52 UTC by AmrEzzEldeen

Feature Booking, SookingType, SubscriptionType entities

2024-03-19 21:45 UTC, Mahmoud-Shosha requested changes
Please check these small notes

2024-03-19 21:45 UTC, Mahmoud-Shosha commented on src/main/java/com/teamc/fms/entity/BookingType.java
> +    private String description;
description column is nullable
![image](https://github.com/web-development-course-way/fms/assets/31379298/5728ba4d-3243-4bd2-8037-6eb3a62b3752)

2024-03-19 21:45 UTC, Mahmoud-Shosha commented on src/main/java/com/teamc/fms/entity/SubscriptionType.java
> +    private String description;
description column is nullable
![image](https://github.com/web-development-course-way/fms/assets/31379298/414d1c8d-8060-479a-b0ed-794af45fef5e)

2024-03-19 21:45 UTC, Mahmoud-Shosha commented on src/main/java/com/teamc/fms/entity/Tenant.java
> +    private LocalDate birthDate;
phonceCode, phoneNumber, nationality and birthdate are nullable
![image](https://github.com/web-development-course-way/fms/assets/31379298/2b8d01b9-3245-4730-a796-d62f87b7c22b)

2024-03-19 23:20 UTC, Mahmoud-Shosha approved these changes
Approved

2024-03-20 19:42 UTC, Muhammed9955 approved these changes

2024-03-20 19:43 UTC, merged