added booking_subscription and booking_timeslot
web-development-course-way/fms pull request #7
Opened 2024-03-20 21:26 UTC by AliRabeeMahmoud

2024-03-20 21:54 UTC, Mahmoud-Shosha requested changes

2024-03-20 21:54 UTC, Mahmoud-Shosha commented on src/main/java/com/teamc/fms/entity/BookingTimeslot.java
> +}
both timeslotId and bookingId are FKs so no need for 
```
@Id
@GeneratedValue(strategy = GenerationType.UUID)
```
So the entity should be     
```
@Data
@Entity
@Table(name = "booking_timeslot")
public class BookingTimeslot {

    @ManyToONe
    private TimeSlot timeslot;

    @ManyToOne
    private Booking booking;
}
```

2024-03-21 17:19 UTC, Mahmoud-Shosha approved these changes

2024-03-21 19:01 UTC, AmrEzzEldeen approved these changes

2024-03-21 19:01 UTC, merged